FROM debian:bookworm-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        openocd \
        python3 \
        python3-pip \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
