FROM debian:bookworm-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        cmake \
        ninja-build \
        git \
        gcc-arm-none-eabi \
        libnewlib-arm-none-eabi \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
